# 作者为电报@yzcjd，2026/4/14

dns:
  enable: true
  listen: 127.0.0.1:1053
  enhanced-mode: fake-ip

  default-nameserver: # 仅用于解析 DoH,平时不干活
    - 223.5.5.5
    - 119.29.29.29

  proxy-server-nameserver: # 让 DNS 请求走代理，否则是直连（慢）
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query

  nameserver: # 访问国内网站
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

  nameserver-policy: # 主要逻辑：国内走直连 DoH（腾讯+阿里），国外走国外 DoH（CF+Google）
    geosite:cn:
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
    geosite:geolocation-!cn:
      - https://1.1.1.1/dns-query
      - https://8.8.8.8/dns-query
