# 作者为电报@yzcjd，2026/4/14


mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: Rule # 似乎必加，才能让国外 DNS 请求走代理
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
profile:
  tracing: true
  
dns:
  enable: true
  listen: 127.0.0.1:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:  # 防异常域名（避免 fake-ip 出问题）
    - '*.lan'
    - localhost
    - '*.local'
    - time.windows.com
    - '*.ntp.org.cn'
    - pool.ntp.org
    - ntp.aliyun.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'

  default-nameserver: # 仅用于解析 DoH,平时不干活。允许少量泄漏
    - 223.5.5.5
    - 119.29.29.29

  proxy-server-nameserver: # 让国外 DNS 请求走代理，运营商看不到咱的请求。
    - https://1.1.1.1/dns-query
    - https://8.8.8.8/dns-query

  nameserver: # 访问国内网站用直连DNS，保证速度
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query

  nameserver-policy: # DNS 分流核心，主要逻辑：国内走直连 DoH（腾讯+阿里），国外走国外 DoH（CF+Google）
    geosite:cn:
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
    geosite:geolocation-!cn:
      - https://1.1.1.1/dns-query
      - https://8.8.8.8/dns-query
