mixed-port: 7890
allow-lan: false
bind-address: '*'
mode: Rule
log-level: info
ipv6: true
hosts:
    services.googleapis.cn: 216.58.200.67
    www.google.cn: 216.58.200.67
external-controller: '0.0.0.0:9090'
clash-for-android:
    append-system-dns: false
profile:
    tracing: true
dns:
    enable: true
    listen: '127.0.0.1:8853'
    default-nameserver: [211.136.192.6, 119.29.29.29, 208.67.220.220, 1.2.4.8]
    nameserver: [211.136.192.6, 119.29.29.29, 208.67.220.220, 1.2.4.8, 8.8.4.4, 8.8.8.8, 'https://8.8.4.4/dns-query', 'https://8.8.8.8/dns-query', 'https://doh.360.cn/dns-query']
    fallback: ['https://dns.rubyfish.cn/dns-query', 'https://doh.pub/dns-query', 'https://rubyfish.cn/dns-query', 'https://public.dns.iij.jp/dns-query', 'tls://8.8.4.4', 'https://cloudflare-dns.com/dns-query', 'https://dns.rubyfish.cn/dns-query', 'https://1.1.1.1/dns-query', 'tls://1.1.1.1:853', 'tls://8.8.8.8:853']
    ipv6: true
    enhanced-mode: fake-ip
    fallback-filter: { geoip: true, geoip-code: CN, ipcidr: [240.0.0.0/4], domain: [+.google.com, +.facebook.com, +.twitter.com, +.tiktokv.com, +.bytedance.map.fastly, +.tiktok.com, +.youtube.com, +.google.cn, +.googleapis.cn, +.googleapis.com, +.gvt1.com] }
nameserver-policy:
    www.baidu.com: 114.114.114.114
    www.taobao.com: 223.5.5.5
    +.internal.crop.com: 10.0.0.1
fake-ip-filter:
    - '*.lan'
    - 'stun.*.*.*'
    - 'stun.*.*'
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - '*.ntp.org.cn'
    - '*.openwrt.pool.ntp.org'
    - time1.cloud.tencent.com
    - time.ustc.edu.cn
    - pool.ntp.org
    - ntp.ubuntu.com
    - ntp.aliyun.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - '*.time.edu.cn'
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - music.163.com
    - '*.music.163.com'
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - '*.y.qq.com'
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - '*.xiami.com'
    - '*.music.migu.cn'
    - music.migu.cn
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - localhost.ptlogin2.qq.com
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - 'xbox.*.*.microsoft.com'
    - '*.ipv6.microsoft.com'
    - '*.*.xboxlive.com'
    - speedtest.cros.wr.pvp.net
