port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
ipv6: true
external-controller: 127.0.0.1:9090
dns:
    - 211.136.192.6
    - 208.67.220.220
    - 1.2.4.8
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
